title: Baleshwar Mahto # your name (or website title) here
logo: "/images/me.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an Electrical Engineering student at School of Enginering , Central University of Karnataka , India .
  <br><br>
  Skills -:<br>
  - Python <br>
  - Matlab <br>
  - Linux <br>
  - C <br>
  - Online Marketing<br>
  <br><br>
  <a href="https://baleshwar2508.github.io/">Home</a> 
  <br><br>
  <a href="mailto:baleshwar2508@gmail.com">Contact me</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/baleshwarmahto/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="/about_me">About me</a> 
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
